language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: 1/3BMmc6IwXn7GCdvM/8UEJvbc1EbHX2d6ljiTHAmWlYBYY1/eECRq5jjAdoDE+5j3unBYF1TPsdhUSiijyBgr3w75RfpyrZUZAAEHM9d/jBfqLKAJf64SfMjQXZyiU13z4iynj3l4SL3N2KfXjJe+eGbcXo904ZvC0+eApL2EWURl3M4De6gOIPtJKMseGHnepKw9DOI29BUGW+U5D7cbIIC6POH8kdnJJl/RG5CUj9R7ATMWaiwOSIHV5yxt/C+9WV8r2c+h09uYfhtdWQoqsjETfkon8w/Ks6UDOilpKGyZJM4PoU6lI+yZTYJU31Qglns6US3gs01G77JQ7VkLl649hrv0xy1UdpGxs04p8AaRuMRQMEZ787NFK6Q5ir2TTLU4mgAruXqEGF/jqFu5Gn7XJ16ZjwxAbfcUSvnX8OagIXLW8o4hwyGjEdtDNWzkQanAJ0gFtn3DAxkx2MI+HZkAEzTgNNpetNiO3gOl5dVIk3W6St9hhNNivxIIBrhA7YhuqdbQ0n7mCQkhnC674fl+l4B65+bFGMaTRjuXuWIP7VHu2DGCOZe6UnpD90aoM4BrLD5uPWp8GWXTN/6agoN00Li8mFsnigEf+Djk/hLzkyjWwYRzBl0wM5oddNFQvz+JMBCqjjyfe1k3eGganpRQ7Rey4l/TvocYAbcBc=
  file: 
    - fs.img
    - xv6.img
  skip_cleanup: true
  on:
    repo: cfainberg/xv6-public
    branch: project_1
    tags: true
