language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: pw5HnterjyaxNnjkbmQJCzy3T1CQbmZTcVs/T+XTcTv5SAf0nkyS+X1ynpIgHBzkbCBDJtQv9kDcreBjYP9/oUYPVjXpfN0vadSbVz63d31nIK8xZWuQ7sTlyHAtL8t9wioUmNBVp3/ryXEULOoWvqkDTxW1jRj90HnTCEk8xIZZehy1Hsl57uu1nuLhEwy+U8wB+SPssqTZkWhed3jzJhRsj9NwD0AaIObYJRLmuxZ0M7u528RdUN1sA1/cbY2rCsgQWiqF1QwoYMzI/BpexQkVWuvKMQRIXgvs8TgUJVeuukYg7izMxQee8LzLYIFhGm/Ix+/7IrjQniz8oI2t4iPRLE6VLnF3l/BIewAPJHBdso4QokjT7m4MW4MNl88msyidKG8KI71gszv83pTZS6XGyT8zujFPw4BnPYeZNZHdO/KtPS51qhzoZyTdi05fO2VHCEl5vH1FSpu2c3SJWNlzIUEqBdmy3WTZ63XRnnrlG67hkvFFSIgAkUa0a2EuA2y4ObJ5ObkpAXeGnwgAi+psrDOBdagdYMK7AO6fAmHrnPmm0exEupqZhEe1Qd2cHPKCDMScgwo6ZysaGYW4uuGM/+shAuXn1aWbuuSsL0SuTUeataR81ASBTI6owJBWbcbPKu2foXJLwLeiroYsDwmR+QbwG2MgWl5rJ+dg1lE=
  file:
  - fs.img
  - xv6.img
  skip_cleanup: true
  on:
    repo: cfainberg/xv6-public
    branch: heads/master
    tags: true

